---

version: "3.8"

services:
  public_api:
    build: ./public_api
    container_name: memes-public-api
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    environment:
      - DB_HOST=main_db
      - DB_PORT=5432
      - DB_NAME=memes
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "5000:5000"
    depends_on:
      - private_api
      - main_db
    networks:
      - memes-net

  private_api:
    build: ./private_api
    container_name: memes-private-api
    command: uvicorn main:app --host 0.0.0.0 --port 5000
    environment:
      - MINIO_ENDPOINT=storage:9000
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=qazxswedcvfr
    ports:
      - "5001:5000"
    depends_on:
      - storage
    networks:
      - memes-net
  
  main_db:
    image: postgres:16
    container_name: memes-main-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memes
    ports:
      - "5432:5432"
    volumes:
      - main_db:/var/lib/postgresql/data
    networks:
      - memes-net

  storage:
    image: minio
    container_name: memes-minio-storage
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=qazxswedcvfr
      - MINIO_LOGS_DIR=/var/log/minio_logs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/bitnami/minio/data
    networks:
      - memes-net

volumes:
  main_db:
  minio_storage:

networks:
  memes-net:
    driver: bridge
  